//HintName: MyApp.AppViewLocator.ViewLocator.g.cs
// <auto-generated/>
#nullable enable

namespace MyApp;

partial class AppViewLocator : global::Avalonia.Controls.Templates.IDataTemplate
{
    private readonly global::System.IServiceProvider _services;

    public AppViewLocator(global::System.IServiceProvider services) => _services = services;

    public global::Avalonia.Controls.Control? Build(object? data) =>
        global::CCSWE.Avalonia.ViewLocator.ViewLocatorResolver.Build(data, _services, GetViewType);

    public bool Match(object? data) => data is not null && GetViewType(data.GetType()) is not null;

    private static global::System.Type? GetViewType(global::System.Type viewModelType)
    {
        if (viewModelType == typeof(global::MyApp.FooViewModel))
            return typeof(global::MyApp.FooView);
        return null;
    }
}
